server:
  port: 8091
spring:
  shardingsphere:
    datasource:
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://120.78.206.144:3306/ds_1?characterEncoding=utf-8
        username: root
      ds2:
        driver-class-name: com.mysql.jdbc.Driver
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://120.78.206.144:3306/ds_2?characterEncoding=utf-8
        username: root
      names: ds1,ds2
    sharding:
      tables:
        book:
          actual-data-nodes: ds1.book
        t_user:
          actual-data-nodes: ds2.t_user